spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbstudies?serverTimezone=America/Sao_Paulo&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: password
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

